import { PublicEvent } from '@/types/countdown';

// Saudi Arabia and International public events
// Events are defined with recurrence types for automatic year rollover:
// - hijri: Islamic calendar events (auto-calculates from Hijri date)
// - fixed-annual: Same Gregorian date every year
// - seasonal: Astronomical/weather events
// - one-time: No recurrence (World Cup, specific year events)

export const publicEvents: PublicEvent[] = [
  // ============================================
  // ISLAMIC/RELIGIOUS EVENTS (Hijri-based)
  // ============================================
  {
    id: 'ramadan-2026',
    baseId: 'ramadan',
    title: 'Ramadan 2026',
    titleAr: 'رمضان ١٤٤٧',
    targetDate: '2026-02-17T00:00:00',
    icon: '🌙',
    theme: 'ramadan',
    category: 'religious',
    dateConfidence: 'estimated',
    dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'الشهر الكريم - شهر الصيام والقرآن',
    recurrenceType: 'hijri',
    hijriDate: { month: 9, day: 1 }, // 1 Ramadan
  },
  {
    id: 'eid-fitr-2026',
    baseId: 'eid-fitr',
    title: 'Eid Al-Fitr 2026',
    titleAr: 'عيد الفطر ١٤٤٧',
    targetDate: '2026-03-19T00:00:00',
    icon: '🎉',
    theme: 'gold',
    category: 'religious',
    dateConfidence: 'estimated',
    dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'عيد الفرحة بعد شهر الصيام',
    recurrenceType: 'hijri',
    hijriDate: { month: 10, day: 1 }, // 1 Shawwal
  },
  {
    id: 'hajj-2026',
    baseId: 'hajj',
    title: 'Hajj Season 2026',
    titleAr: 'موسم الحج ١٤٤٧',
    targetDate: '2026-05-24T00:00:00',
    icon: '🕋',
    theme: 'gold',
    category: 'religious',
    dateConfidence: 'estimated',
    dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'الركن الخامس من أركان الإسلام',
    recurrenceType: 'hijri',
    hijriDate: { month: 12, day: 8 }, // 8 Dhul Hijjah (start of Hajj)
  },
  {
    id: 'eid-adha-2026',
    baseId: 'eid-adha',
    title: 'Eid Al-Adha 2026',
    titleAr: 'عيد الأضحى ١٤٤٧',
    targetDate: '2026-05-26T00:00:00',
    icon: '🐑',
    theme: 'gold',
    category: 'religious',
    dateConfidence: 'estimated',
    dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'عيد الأضحية - ذكرى فداء إسماعيل عليه السلام',
    recurrenceType: 'hijri',
    hijriDate: { month: 12, day: 10 }, // 10 Dhul Hijjah
  },
  {
    id: 'lailat-al-qadr-2026', baseId: 'lailat-al-qadr',
    title: 'Lailat Al-Qadr 2026', titleAr: 'رمضان ١٤٤٧ - ليلة القدر',
    targetDate: '2026-03-15T00:00:00',
    icon: '✨', theme: 'ramadan', category: 'religious',
    dateConfidence: 'estimated', dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'ليلة خير من ألف شهر - تُحيا في العشر الأواخر من رمضان',
    recurrenceType: 'hijri', hijriDate: { month: 9, day: 27 },
  },
  {
    id: 'islamic-new-year-1448', baseId: 'islamic-new-year',
    title: 'Islamic New Year 1448', titleAr: 'السنة الهجرية الجديدة ١٤٤٨',
    targetDate: '2026-06-17T00:00:00',
    icon: '🌙', theme: 'ramadan', category: 'religious',
    dateConfidence: 'estimated', dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'مستهل السنة الهجرية الجديدة ١٤٤٨',
    recurrenceType: 'hijri', hijriDate: { month: 1, day: 1 },
  },
  {
    id: 'mawlid-al-nabi-1448', baseId: 'mawlid-al-nabi',
    title: 'Mawlid Al-Nabi 1448', titleAr: 'المولد النبوي الشريف ١٤٤٨',
    targetDate: '2026-09-04T00:00:00',
    icon: '🕌', theme: 'gold', category: 'religious',
    dateConfidence: 'estimated', dateSource: 'Hijri Calendar Calculation',
    isHijriDerived: true,
    note: 'ذكرى مولد سيد المرسلين صلى الله عليه وسلم',
    recurrenceType: 'hijri', hijriDate: { month: 3, day: 12 },
  },

  // ============================================
  // SAUDI NATIONAL EVENTS (Fixed Annual)
  // ============================================
  {
    id: 'founding-day-2026',
    baseId: 'founding-day',
    title: 'Founding Day 2026',
    titleAr: 'يوم التأسيس ٢٠٢٦',
    targetDate: '2026-02-22T00:00:00',
    icon: '🇸🇦',
    theme: 'default',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'Royal Decree 2022',
    note: 'ذكرى تأسيس الدولة السعودية الأولى ١٧٢٧م',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 2, day: 22 }, // February 22
  },
  {
    id: 'flag-day-2026',
    baseId: 'flag-day',
    title: 'Flag Day 2026',
    titleAr: 'يوم العلم ٢٠٢٦',
    targetDate: '2026-03-11T00:00:00',
    icon: '🇸🇦',
    theme: 'default',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'Royal Decree 2023',
    note: 'احتفاء بالعلم السعودي ورمزيته الوطنية',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 3, day: 11 }, // March 11
  },
  {
    id: 'national-day-2026',
    baseId: 'national-day',
    title: 'National Day 2026',
    titleAr: 'اليوم الوطني ٢٠٢٦',
    targetDate: '2026-09-23T00:00:00',
    icon: '🇸🇦',
    theme: 'default',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'Fixed since 1932',
    note: 'الذكرى ٩٦ لتوحيد المملكة العربية السعودية',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 9, day: 23 }, // September 23
  },

  // ============================================
  // SAUDI SEASONS (Seasonal - Weather & Stars)
  // ============================================
  {
    id: 'summer-start-2026',
    baseId: 'summer-start',
    title: 'Summer Begins',
    titleAr: 'بداية الصيف ٢٠٢٦',
    targetDate: '2026-06-21T00:00:00',
    icon: '☀️',
    theme: 'sunset',
    category: 'seasonal',
    dateConfidence: 'confirmed',
    dateSource: 'Astronomical Calendar',
    note: 'الانقلاب الصيفي - أطول نهار في السنة',
    recurrenceType: 'seasonal',
    fixedDate: { month: 6, day: 21 },
  },
  {
    id: 'spring-equinox-2026', baseId: 'spring-equinox',
    title: 'Spring Equinox 2026', titleAr: 'بداية فصل الربيع ٢٠٢٦',
    targetDate: '2026-03-20T00:00:00',
    icon: '🌸', theme: 'sunset', category: 'seasonal',
    dateConfidence: 'confirmed', dateSource: 'Astronomical Calendar',
    note: 'الاعتدال الربيعي - تساوي الليل والنهار',
    recurrenceType: 'seasonal', fixedDate: { month: 3, day: 20 },
  },
  {
    id: 'suhail-2026',
    baseId: 'suhail',
    title: 'Suhail Star Rising',
    titleAr: 'طلوع سهيل ٢٠٢٦',
    targetDate: '2026-08-24T00:00:00',
    icon: '⭐',
    theme: 'night',
    category: 'seasonal',
    dateConfidence: 'confirmed',
    dateSource: 'Arabian Star Calendar',
    note: 'بشير انكسار الحرارة - يقول المثل: إذا طلع سهيل، لطّف الليل',
    recurrenceType: 'seasonal',
    fixedDate: { month: 8, day: 24 },
  },
  {
    id: 'al-wasm-2026',
    baseId: 'al-wasm',
    title: 'Al-Wasm Season',
    titleAr: 'موسم الوسم ٢٠٢٦',
    targetDate: '2026-10-16T00:00:00',
    icon: '🌧️',
    theme: 'default',
    category: 'seasonal',
    dateConfidence: 'confirmed',
    dateSource: 'Arabian Star Calendar',
    note: 'موسم الأمطار وبداية الخضرة في الصحراء',
    recurrenceType: 'seasonal',
    fixedDate: { month: 10, day: 16 },
  },
  {
    id: 'al-aqrab-2026',
    baseId: 'al-aqrab',
    title: 'Al-Aqrab Season',
    titleAr: 'موسم العقرب ٢٠٢٦',
    targetDate: '2026-11-16T00:00:00',
    icon: '🦂',
    theme: 'sunset',
    category: 'seasonal',
    dateConfidence: 'confirmed',
    dateSource: 'Arabian Star Calendar',
    note: 'بداية أقسى فترات البرد - ٤٠ يوم',
    recurrenceType: 'seasonal',
    fixedDate: { month: 11, day: 16 },
  },
  {
    id: 'winter-start-2026',
    baseId: 'winter-start',
    title: 'Winter Begins',
    titleAr: 'بداية الشتاء ٢٠٢٦',
    targetDate: '2026-12-21T00:00:00',
    icon: '❄️',
    theme: 'night',
    category: 'seasonal',
    dateConfidence: 'confirmed',
    dateSource: 'Astronomical Calendar',
    note: 'الانقلاب الشتوي - أقصر نهار في السنة',
    recurrenceType: 'seasonal',
    fixedDate: { month: 12, day: 21 },
  },

  // ============================================
  // ANNUAL INTERNATIONAL EVENTS (Fixed Annual)
  // ============================================
  {
    id: 'new-year-2027',
    baseId: 'new-year',
    title: 'New Year 2027',
    titleAr: 'السنة الجديدة ٢٠٢٧',
    targetDate: '2027-01-01T00:00:00',
    icon: '🎊',
    theme: 'night',
    category: 'international',
    dateConfidence: 'confirmed',
    dateSource: 'Fixed Date',
    note: 'استقبال العام الجديد حول العالم',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 1, day: 1 },
  },

  // ============================================
  // ENTERTAINMENT (Tentative Annual)
  // ============================================
  {
    id: 'riyadh-season-2026',
    baseId: 'riyadh-season',
    title: 'Riyadh Season 2026',
    titleAr: 'موسم الرياض ٢٠٢٦',
    targetDate: '2026-10-15T00:00:00',
    icon: '🎭',
    theme: 'sunset',
    category: 'entertainment',
    dateConfidence: 'tentative',
    dateSource: 'GEA (pending confirmation)',
    note: 'أكبر موسم ترفيهي في الشرق الأوسط',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 10, day: 15 },
  },

  // ============================================
  // ONE-TIME EVENTS (No Recurrence)
  // ============================================
  {
    id: 'worldcup-2026',
    baseId: 'worldcup-2026',
    title: 'FIFA World Cup 2026',
    titleAr: 'كأس العالم ٢٠٢٦',
    targetDate: '2026-06-11T00:00:00',
    icon: '⚽',
    theme: 'gold',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'FIFA Official',
    note: 'أكبر نسخة في التاريخ - ٤٨ منتخب في أمريكا وكندا والمكسيك',
    recurrenceType: 'one-time',
  },
  {
    id: 'apple-event-2026',
    baseId: 'apple-event-2026',
    title: 'Apple September Event',
    titleAr: 'حدث آبل سبتمبر ٢٠٢٦',
    targetDate: '2026-09-08T00:00:00',
    icon: '📱',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Apple (Expected)',
    note: 'الكشف عن iPhone 18 والأجهزة الجديدة',
    recurrenceType: 'one-time',
  },
  {
    id: 'us-elections-2026',
    baseId: 'us-elections-2026',
    title: 'US Midterm Elections',
    titleAr: 'انتخابات أمريكا النصفية',
    targetDate: '2026-11-03T00:00:00',
    icon: '🗳️',
    theme: 'default',
    category: 'political',
    dateConfidence: 'confirmed',
    dateSource: 'US Federal Election Commission',
    note: 'انتخابات الكونغرس النصفية',
    recurrenceType: 'one-time',
  },

  // ============================================
  // MILESTONE EVENTS (One-time, far future)
  // ============================================
  {
    id: 'vision-2030',
    baseId: 'vision-2030',
    title: 'Vision 2030',
    titleAr: 'رؤية السعودية ٢٠٣٠',
    targetDate: '2030-12-31T00:00:00',
    icon: '🚀',
    theme: 'gold',
    category: 'milestone',
    dateConfidence: 'confirmed',
    dateSource: 'Vision 2030 Program',
    note: 'مستقبل المملكة - تنويع الاقتصاد وجودة الحياة',
    recurrenceType: 'one-time',
  },
  {
    id: 'expo-2030',
    baseId: 'expo-2030',
    title: 'Expo 2030 Riyadh',
    titleAr: 'إكسبو الرياض ٢٠٣٠',
    targetDate: '2030-10-01T00:00:00',
    icon: '🌍',
    theme: 'gold',
    category: 'milestone',
    dateConfidence: 'confirmed',
    dateSource: 'BIE Official',
    note: 'الرياض تستضيف العالم تحت شعار "حقبة التغيير"',
    recurrenceType: 'one-time',
  },
  {
    id: 'worldcup-2034',
    baseId: 'worldcup-2034',
    title: 'FIFA World Cup 2034',
    titleAr: 'كأس العالم السعودية ٢٠٣٤',
    targetDate: '2034-11-01T00:00:00',
    icon: '🏆',
    theme: 'gold',
    category: 'milestone',
    dateConfidence: 'confirmed',
    dateSource: 'FIFA Official',
    note: 'المملكة تستضيف كأس العالم لأول مرة!',
    recurrenceType: 'one-time',
  },
  {
    id: 'saudi-green-initiative-2030', baseId: 'saudi-green-initiative-2030',
    title: 'Saudi Green Initiative 2030', titleAr: 'مبادرة السعودية الخضراء ٢٠٣٠',
    targetDate: '2030-12-31T00:00:00',
    icon: '🌱', theme: 'default', category: 'milestone',
    dateConfidence: 'tentative', dateSource: 'Ministry of Environment',
    note: 'هدف زراعة ١٠ مليار شجرة في إطار مبادرة السعودية الخضراء',
    recurrenceType: 'one-time',
  },

  // ============================================
  // TECH EVENTS
  // ============================================
  {
    id: 'wwdc-2026',
    baseId: 'wwdc-2026',
    title: 'WWDC 2026',
    titleAr: 'مؤتمر آبل للمطورين ٢٠٢٦',
    targetDate: '2026-06-08T00:00:00',
    icon: '💻',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Apple (Expected Annual)',
    note: 'مؤتمر المطورين السنوي من آبل - iOS وmacOS الجديد',
    recurrenceType: 'one-time',
  },
  {
    id: 'google-io-2026',
    baseId: 'google-io-2026',
    title: 'Google I/O 2026',
    titleAr: 'مؤتمر Google I/O ٢٠٢٦',
    targetDate: '2026-05-19T00:00:00',
    icon: '🔍',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Google (Expected Annual)',
    note: 'المؤتمر السنوي لمطوري Google - AI والأندرويد الجديد',
    recurrenceType: 'one-time',
  },
  {
    id: 'microsoft-build-2026',
    baseId: 'microsoft-build-2026',
    title: 'Microsoft Build 2026',
    titleAr: 'مؤتمر Microsoft Build ٢٠٢٦',
    targetDate: '2026-05-20T00:00:00',
    icon: '🪟',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Microsoft (Expected Annual)',
    note: 'مؤتمر مطوري مايكروسوفت - Azure وCopilot والذكاء الاصطناعي',
    recurrenceType: 'one-time',
  },
  {
    id: 'meta-connect-2026',
    baseId: 'meta-connect-2026',
    title: 'Meta Connect 2026',
    titleAr: 'مؤتمر Meta Connect ٢٠٢٦',
    targetDate: '2026-09-25T00:00:00',
    icon: '🥽',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Meta (Expected Annual)',
    note: 'حدث الواقع الافتراضي والمعزز من ميتا - Quest الجديد',
    recurrenceType: 'one-time',
  },
  {
    id: 'ces-2027',
    baseId: 'ces',
    title: 'CES 2027',
    titleAr: 'معرض CES 2027',
    targetDate: '2027-01-05T00:00:00',
    icon: '🖥️',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'confirmed',
    dateSource: 'CTA (Consumer Technology Association)',
    note: 'أكبر معرض تكنولوجي في العالم - لاس فيغاس',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 1, day: 5 },
  },
  {
    id: 'samsung-unpacked-2027',
    baseId: 'samsung-unpacked-2027',
    title: 'Samsung Galaxy Unpacked 2027',
    titleAr: 'إطلاق سامسونج Galaxy ٢٠٢٧',
    targetDate: '2027-01-22T00:00:00',
    icon: '📲',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Samsung (Expected Annual)',
    note: 'الكشف عن Galaxy S27 وأحدث أجهزة سامسونج',
    recurrenceType: 'one-time',
  },
  {
    id: 'leap-2027',
    baseId: 'leap',
    title: 'LEAP 2027',
    titleAr: 'مؤتمر LEAP 2027',
    targetDate: '2027-02-09T00:00:00',
    icon: '🚀',
    theme: 'gold',
    category: 'tech',
    dateConfidence: 'confirmed',
    dateSource: 'LEAP Official',
    note: 'أكبر مؤتمر تقني في الشرق الأوسط - الرياض',
    recurrenceType: 'one-time',
  },
  {
    id: 'black-friday-2026',
    baseId: 'black-friday',
    title: 'Black Friday 2026',
    titleAr: 'الجمعة البيضاء ٢٠٢٦',
    targetDate: '2026-11-27T00:00:00',
    icon: '🛍️',
    theme: 'night',
    category: 'tech',
    dateConfidence: 'confirmed',
    dateSource: 'Fixed Date (4th Friday of November)',
    note: 'أكبر يوم تسوق في العالم - تخفيضات ضخمة على الإلكترونيات',
    recurrenceType: 'one-time',
  },
  {
    id: 'amazon-prime-day-2026',
    baseId: 'amazon-prime-day-2026',
    title: 'Amazon Prime Day 2026',
    titleAr: 'Amazon Prime Day ٢٠٢٦',
    targetDate: '2026-07-08T00:00:00',
    icon: '📦',
    theme: 'default',
    category: 'tech',
    dateConfidence: 'tentative',
    dateSource: 'Amazon (Expected Annual)',
    note: 'يومان من العروض الحصرية لأعضاء Amazon Prime',
    recurrenceType: 'one-time',
  },
  {
    id: 'aws-reinvent-2026', baseId: 'aws-reinvent',
    title: 'AWS re:Invent 2026', titleAr: 'مؤتمر AWS re:Invent ٢٠٢٦',
    targetDate: '2026-12-01T00:00:00',
    icon: '☁️', theme: 'night', category: 'tech',
    dateConfidence: 'confirmed', dateSource: 'Amazon Web Services',
    note: 'أكبر مؤتمر للحوسبة السحابية - لاس فيغاس',
    recurrenceType: 'fixed-annual', fixedDate: { month: 12, day: 1 },
  },
  {
    id: 'openai-devday-2026', baseId: 'openai-devday-2026',
    title: 'OpenAI DevDay 2026', titleAr: 'يوم المطورين من OpenAI ٢٠٢٦',
    targetDate: '2026-11-05T00:00:00',
    icon: '🤖', theme: 'night', category: 'tech',
    dateConfidence: 'tentative', dateSource: 'OpenAI (Expected Annual)',
    note: 'مؤتمر مطوري OpenAI - إعلانات ChatGPT وGPT الجديدة',
    recurrenceType: 'one-time',
  },
  {
    id: 'github-universe-2026', baseId: 'github-universe-2026',
    title: 'GitHub Universe 2026', titleAr: 'GitHub Universe ٢٠٢٦',
    targetDate: '2026-10-29T00:00:00',
    icon: '🐙', theme: 'night', category: 'tech',
    dateConfidence: 'tentative', dateSource: 'GitHub (Expected Annual)',
    note: 'المؤتمر السنوي لمجتمع مطوري GitHub',
    recurrenceType: 'one-time',
  },

  // ============================================
  // GAMING EVENTS
  // ============================================
  {
    id: 'gta-vi-2026',
    baseId: 'gta-vi-2026',
    title: 'GTA VI Release',
    titleAr: 'إصدار GTA VI',
    targetDate: '2026-05-26T00:00:00',
    icon: '🎮',
    theme: 'night',
    category: 'gaming',
    dateConfidence: 'confirmed',
    dateSource: 'Rockstar Games Official',
    note: 'أكثر لعبة ترقباً في التاريخ - العودة إلى Vice City',
    recurrenceType: 'one-time',
  },
  {
    id: 'summer-game-fest-2026',
    baseId: 'summer-game-fest-2026',
    title: 'Summer Game Fest 2026',
    titleAr: 'مهرجان ألعاب الصيف ٢٠٢٦',
    targetDate: '2026-06-09T00:00:00',
    icon: '🎯',
    theme: 'default',
    category: 'gaming',
    dateConfidence: 'tentative',
    dateSource: 'Geoff Keighley (Expected Annual)',
    note: 'أكبر حدث للإعلان عن ألعاب الفيديو القادمة',
    recurrenceType: 'one-time',
  },
  {
    id: 'xbox-showcase-2026',
    baseId: 'xbox-showcase-2026',
    title: 'Xbox Games Showcase 2026',
    titleAr: 'عرض Xbox للألعاب ٢٠٢٦',
    targetDate: '2026-06-11T00:00:00',
    icon: '🟩',
    theme: 'default',
    category: 'gaming',
    dateConfidence: 'tentative',
    dateSource: 'Microsoft (Expected Annual)',
    note: 'مؤتمر Xbox السنوي - Game Pass وألعاب جديدة',
    recurrenceType: 'one-time',
  },
  {
    id: 'playstation-showcase-2026',
    baseId: 'playstation-showcase-2026',
    title: 'PlayStation Showcase 2026',
    titleAr: 'عرض PlayStation ٢٠٢٦',
    targetDate: '2026-05-15T00:00:00',
    icon: '🎮',
    theme: 'night',
    category: 'gaming',
    dateConfidence: 'tentative',
    dateSource: 'Sony (Expected)',
    note: 'إعلانات PlayStation 5 والألعاب الحصرية القادمة',
    recurrenceType: 'one-time',
  },
  {
    id: 'gamescom-2026',
    baseId: 'gamescom',
    title: 'Gamescom 2026',
    titleAr: 'معرض Gamescom 2026',
    targetDate: '2026-08-27T00:00:00',
    icon: '🕹️',
    theme: 'default',
    category: 'gaming',
    dateConfidence: 'confirmed',
    dateSource: 'Koelnmesse GmbH',
    note: 'أكبر معرض للألعاب في العالم - كولونيا، ألمانيا',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 8, day: 27 },
  },
  {
    id: 'esports-wc-2026',
    baseId: 'esports-wc-2026',
    title: 'Esports World Cup 2026',
    titleAr: 'كأس العالم للرياضات الإلكترونية ٢٠٢٦',
    targetDate: '2026-07-10T00:00:00',
    icon: '🏆',
    theme: 'gold',
    category: 'gaming',
    dateConfidence: 'confirmed',
    dateSource: 'Esports World Cup Foundation',
    note: 'أكبر بطولة إلكترونية في العالم - الرياض',
    recurrenceType: 'one-time',
  },
  {
    id: 'game-awards-2026',
    baseId: 'game-awards',
    title: 'The Game Awards 2026',
    titleAr: 'حفل جوائز الألعاب ٢٠٢٦',
    targetDate: '2026-12-10T00:00:00',
    icon: '🏅',
    theme: 'gold',
    category: 'gaming',
    dateConfidence: 'tentative',
    dateSource: 'Geoff Keighley (Expected Annual)',
    note: 'حفل جوائز ألعاب الفيديو الأبرز في العالم',
    recurrenceType: 'one-time',
  },
  {
    id: 'nintendo-direct-2026',
    baseId: 'nintendo-direct-2026',
    title: 'Nintendo Direct 2026',
    titleAr: 'نينتندو دايركت ٢٠٢٦',
    targetDate: '2026-06-18T00:00:00',
    icon: '🔴',
    theme: 'default',
    category: 'gaming',
    dateConfidence: 'tentative',
    dateSource: 'Nintendo (Expected Annual)',
    note: 'إعلانات Nintendo Switch 2 والألعاب القادمة',
    recurrenceType: 'one-time',
  },

  // ============================================
  // SPORTS EVENTS
  // ============================================
  {
    id: 'roland-garros-2026',
    baseId: 'roland-garros',
    title: 'Roland Garros 2026',
    titleAr: 'بطولة رولان غاروس ٢٠٢٦',
    targetDate: '2026-05-25T00:00:00',
    icon: '🎾',
    theme: 'sunset',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'French Tennis Federation',
    note: 'بطولة فرنسا المفتوحة للتنس - أشهر ملاعب الغرانيت الأحمر',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 5, day: 25 },
  },
  {
    id: 'wimbledon-2026',
    baseId: 'wimbledon',
    title: 'Wimbledon 2026',
    titleAr: 'بطولة ويمبلدون ٢٠٢٦',
    targetDate: '2026-06-29T00:00:00',
    icon: '🎾',
    theme: 'default',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'All England Club',
    note: 'أعرق بطولات التنس في العالم - لندن',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 6, day: 29 },
  },
  {
    id: 'us-open-tennis-2026',
    baseId: 'us-open-tennis',
    title: 'US Open Tennis 2026',
    titleAr: 'بطولة أمريكا المفتوحة ٢٠٢٦',
    targetDate: '2026-08-31T00:00:00',
    icon: '🎾',
    theme: 'night',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'USTA',
    note: 'بطولة أمريكا المفتوحة للتنس - نيويورك',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 8, day: 31 },
  },
  {
    id: 'afc-asian-cup-2027',
    baseId: 'afc-asian-cup-2027',
    title: 'AFC Asian Cup 2027',
    titleAr: 'كأس آسيا ٢٠٢٧ - السعودية',
    targetDate: '2027-01-05T00:00:00',
    icon: '🏆',
    theme: 'gold',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'AFC Official',
    note: 'المملكة العربية السعودية تستضيف بطولة كأس آسيا لكرة القدم',
    recurrenceType: 'one-time',
  },
  {
    id: 'f1-saudi-gp-2027',
    baseId: 'f1-saudi-gp',
    title: 'Formula 1 Saudi Arabian GP 2027',
    titleAr: 'جائزة السعودية الكبرى - Formula 1 ٢٠٢٧',
    targetDate: '2027-03-28T00:00:00',
    icon: '🏎️',
    theme: 'default',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'FIA Formula One',
    note: 'الجائزة الكبرى السعودية للفورمولا 1 - جدة كورنيش',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 3, day: 28 },
  },
  {
    id: 'dakar-rally-2027',
    baseId: 'dakar-rally',
    title: 'Dakar Rally 2027',
    titleAr: 'رالي داكار ٢٠٢٧',
    targetDate: '2027-01-03T00:00:00',
    icon: '🏜️',
    theme: 'sunset',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'ASO (Amaury Sport Organisation)',
    note: 'أصعب سباق رالي في العالم - يُقام في السعودية منذ 2020',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 1, day: 3 },
  },
  {
    id: 'olympics-2028',
    baseId: 'olympics-2028',
    title: 'Los Angeles Olympics 2028',
    titleAr: 'الألعاب الأولمبية لوس أنجلوس ٢٠٢٨',
    targetDate: '2028-07-14T00:00:00',
    icon: '🥇',
    theme: 'gold',
    category: 'sports',
    dateConfidence: 'confirmed',
    dateSource: 'IOC Official',
    note: 'الألعاب الأولمبية الصيفية - لوس أنجلوس، كاليفورنيا',
    recurrenceType: 'one-time',
  },
  {
    id: 'saudi-pro-league-final-2026',
    baseId: 'saudi-pro-league-final-2026',
    title: 'Saudi Pro League Final 2026',
    titleAr: 'نهائي الدوري السعودي ٢٠٢٦',
    targetDate: '2026-06-12T00:00:00',
    icon: '⚽',
    theme: 'gold',
    category: 'sports',
    dateConfidence: 'tentative',
    dateSource: 'SAFF (Expected)',
    note: 'نهاية موسم الدوري السعودي للمحترفين 2025/2026',
    recurrenceType: 'one-time',
  },
  {
    id: 'australian-open-2027', baseId: 'australian-open',
    title: 'Australian Open 2027', titleAr: 'بطولة أستراليا المفتوحة ٢٠٢٧',
    targetDate: '2027-01-18T00:00:00',
    icon: '🎾', theme: 'sunset', category: 'sports',
    dateConfidence: 'confirmed', dateSource: 'Tennis Australia',
    note: 'أولى بطولات غراند سلام في العام - ملبورن، أستراليا',
    recurrenceType: 'fixed-annual', fixedDate: { month: 1, day: 18 },
  },
  {
    id: 'saudi-kings-cup-final-2026', baseId: 'saudi-kings-cup-final-2026',
    title: "Saudi King's Cup Final 2026", titleAr: 'نهائي كأس الملك السعودي ٢٠٢٦',
    targetDate: '2026-05-30T00:00:00',
    icon: '🏆', theme: 'gold', category: 'sports',
    dateConfidence: 'tentative', dateSource: 'SAFF (Expected)',
    note: 'نهائي كأس الملك لكرة القدم السعودي',
    recurrenceType: 'one-time',
  },

  // ============================================
  // FINANCE EVENTS
  // ============================================
  {
    id: 'aramco-q1-2026',
    baseId: 'aramco-q1-2026',
    title: 'Aramco Q1 2026 Results',
    titleAr: 'نتائج أرامكو الربع الأول ٢٠٢٦',
    targetDate: '2026-03-15T00:00:00',
    icon: '🛢️',
    theme: 'gold',
    category: 'finance',
    dateConfidence: 'tentative',
    dateSource: 'Saudi Aramco IR',
    note: 'إعلان نتائج أرامكو للربع الأول من عام 2026',
    recurrenceType: 'one-time',
  },
  {
    id: 'opec-jun-2026',
    baseId: 'opec-jun-2026',
    title: 'OPEC+ Meeting June 2026',
    titleAr: 'اجتماع أوبك+ يونيو ٢٠٢٦',
    targetDate: '2026-06-01T00:00:00',
    icon: '🛢️',
    theme: 'default',
    category: 'finance',
    dateConfidence: 'tentative',
    dateSource: 'OPEC Secretariat',
    note: 'اجتماع منظمة الدول المصدرة للنفط لتحديد مستويات الإنتاج',
    recurrenceType: 'one-time',
  },
  {
    id: 'aramco-q2-2026',
    baseId: 'aramco-q2-2026',
    title: 'Aramco Q2 2026 Results',
    titleAr: 'نتائج أرامكو الربع الثاني ٢٠٢٦',
    targetDate: '2026-06-15T00:00:00',
    icon: '🛢️',
    theme: 'gold',
    category: 'finance',
    dateConfidence: 'tentative',
    dateSource: 'Saudi Aramco IR',
    note: 'إعلان نتائج أرامكو للربع الثاني من عام 2026',
    recurrenceType: 'one-time',
  },
  {
    id: 'opec-dec-2026',
    baseId: 'opec-dec-2026',
    title: 'OPEC+ Meeting December 2026',
    titleAr: 'اجتماع أوبك+ ديسمبر ٢٠٢٦',
    targetDate: '2026-12-01T00:00:00',
    icon: '🛢️',
    theme: 'default',
    category: 'finance',
    dateConfidence: 'tentative',
    dateSource: 'OPEC Secretariat',
    note: 'الاجتماع الختامي لأوبك+ لعام 2026 لتحديد خطة 2027',
    recurrenceType: 'one-time',
  },
  {
    id: 'saudi-budget-2026',
    baseId: 'saudi-budget-2026',
    title: 'Saudi Budget 2026 Announcement',
    titleAr: 'الميزانية السعودية ٢٠٢٦',
    targetDate: '2026-12-09T00:00:00',
    icon: '💰',
    theme: 'gold',
    category: 'finance',
    dateConfidence: 'tentative',
    dateSource: 'Ministry of Finance (Expected Annual ~December)',
    note: 'إعلان الميزانية العامة للدولة للسنة المالية القادمة',
    recurrenceType: 'one-time',
  },
  {
    id: 'saudi-fiscal-year-end-2026',
    baseId: 'saudi-fiscal-year-end',
    title: 'Saudi Fiscal Year End 2026',
    titleAr: 'نهاية السنة المالية السعودية ٢٠٢٦',
    targetDate: '2026-12-31T00:00:00',
    icon: '📊',
    theme: 'default',
    category: 'finance',
    dateConfidence: 'confirmed',
    dateSource: 'Ministry of Finance',
    note: 'نهاية السنة المالية للمملكة - ديسمبر 31',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 12, day: 31 },
  },
  {
    id: 'davos-2027',
    baseId: 'davos',
    title: 'Davos 2027',
    titleAr: 'منتدى دافوس الاقتصادي ٢٠٢٧',
    targetDate: '2027-01-20T00:00:00',
    icon: '🌐',
    theme: 'night',
    category: 'finance',
    dateConfidence: 'confirmed',
    dateSource: 'World Economic Forum',
    note: 'المنتدى الاقتصادي العالمي - دافوس، سويسرا',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 1, day: 20 },
  },
  {
    id: 'aramco-q3-2026', baseId: 'aramco-q3-2026',
    title: 'Aramco Q3 2026 Results', titleAr: 'نتائج أرامكو الربع الثالث ٢٠٢٦',
    targetDate: '2026-09-15T00:00:00',
    icon: '🛢️', theme: 'gold', category: 'finance',
    dateConfidence: 'tentative', dateSource: 'Saudi Aramco IR',
    note: 'إعلان نتائج أرامكو للربع الثالث من عام 2026',
    recurrenceType: 'one-time',
  },
  {
    id: 'neom-progress-2026', baseId: 'neom-progress-2026',
    title: 'NEOM Progress Report 2026', titleAr: 'تقرير تقدم نيوم ٢٠٢٦',
    targetDate: '2026-12-15T00:00:00',
    icon: '🌆', theme: 'gold', category: 'finance',
    dateConfidence: 'tentative', dateSource: 'NEOM (Expected Annual)',
    note: 'تقرير الإنجازات السنوي لمشروع نيوم',
    recurrenceType: 'one-time',
  },

  // ============================================
  // POLITICAL EVENTS
  // ============================================
  {
    id: 'un-general-assembly-2026',
    baseId: 'un-general-assembly',
    title: 'UN General Assembly 2026',
    titleAr: 'الجمعية العامة للأمم المتحدة ٢٠٢٦',
    targetDate: '2026-09-16T00:00:00',
    icon: '🇺🇳',
    theme: 'default',
    category: 'political',
    dateConfidence: 'confirmed',
    dateSource: 'United Nations',
    note: 'الدورة السنوية للجمعية العامة للأمم المتحدة - نيويورك',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 9, day: 16 },
  },
  {
    id: 'g20-2026',
    baseId: 'g20-2026',
    title: 'G20 Summit 2026',
    titleAr: 'قمة مجموعة العشرين ٢٠٢٦',
    targetDate: '2026-11-15T00:00:00',
    icon: '🌍',
    theme: 'default',
    category: 'political',
    dateConfidence: 'tentative',
    dateSource: 'G20 South Africa Presidency',
    note: 'قمة مجموعة العشرين في جنوب أفريقيا',
    recurrenceType: 'one-time',
  },
  {
    id: 'arab-league-summit-2026',
    baseId: 'arab-league-summit-2026',
    title: 'Arab League Summit 2026',
    titleAr: 'القمة العربية ٢٠٢٦',
    targetDate: '2026-05-01T00:00:00',
    icon: '🌙',
    theme: 'default',
    category: 'political',
    dateConfidence: 'tentative',
    dateSource: 'Arab League Secretariat',
    note: 'القمة العربية السنوية لرؤساء الدول العربية',
    recurrenceType: 'one-time',
  },
  {
    id: 'french-presidential-2027',
    baseId: 'french-presidential-2027',
    title: 'French Presidential Election 2027',
    titleAr: 'الانتخابات الرئاسية الفرنسية ٢٠٢٧',
    targetDate: '2027-04-11T00:00:00',
    icon: '🗳️',
    theme: 'default',
    category: 'political',
    dateConfidence: 'confirmed',
    dateSource: 'French Constitutional Council',
    note: 'الانتخابات الرئاسية الفرنسية - الجولة الأولى',
    recurrenceType: 'one-time',
  },

  // ============================================
  // MORE NATIONAL EVENTS (Fixed Annual)
  // ============================================
  {
    id: 'arab-mothers-day',
    baseId: 'arab-mothers-day',
    title: 'Arab Mother\'s Day',
    titleAr: 'يوم الأم العربي',
    targetDate: '2026-03-21T00:00:00',
    icon: '💐',
    theme: 'sunset',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'Fixed Date (March 21)',
    note: 'يوم الأم في الدول العربية - ٢١ مارس',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 3, day: 21 },
  },
  {
    id: 'teachers-day',
    baseId: 'teachers-day',
    title: 'World Teachers Day',
    titleAr: 'يوم المعلم العالمي',
    targetDate: '2026-10-05T00:00:00',
    icon: '📖',
    theme: 'default',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'UNESCO (Fixed: October 5)',
    note: 'يوم عالمي لتكريم المعلمين والمعلمات',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 10, day: 5 },
  },
  {
    id: 'arabic-language-day',
    baseId: 'arabic-language-day',
    title: 'World Arabic Language Day',
    titleAr: 'اليوم العالمي للغة العربية',
    targetDate: '2026-12-18T00:00:00',
    icon: '🖊️',
    theme: 'gold',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'UNESCO (Fixed: December 18)',
    note: 'يوم الاحتفاء بأجمل لغات العالم وأكثرها تعبيراً',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 12, day: 18 },
  },
  {
    id: 'gcc-national-day',
    baseId: 'gcc-national-day',
    title: 'GCC National Day',
    titleAr: 'يوم مجلس التعاون الخليجي',
    targetDate: '2026-05-25T00:00:00',
    icon: '🌟',
    theme: 'gold',
    category: 'national',
    dateConfidence: 'confirmed',
    dateSource: 'GCC Secretariat (Fixed: May 25)',
    note: 'ذكرى تأسيس مجلس التعاون لدول الخليج العربية ١٩٨١',
    recurrenceType: 'fixed-annual',
    fixedDate: { month: 5, day: 25 },
  },
  {
    id: 'arab-youth-day-2026', baseId: 'arab-youth-day',
    title: 'Arab Youth Day 2026', titleAr: 'يوم الشباب العربي ٢٠٢٦',
    targetDate: '2026-08-12T00:00:00',
    icon: '🌟', theme: 'gold', category: 'national',
    dateConfidence: 'confirmed', dateSource: 'Arab League (Fixed: August 12)',
    note: 'يوم الاحتفاء بشباب الأمة العربية',
    recurrenceType: 'fixed-annual', fixedDate: { month: 8, day: 12 },
  },

  // ============================================
  // MORE ENTERTAINMENT EVENTS
  // ============================================
  {
    id: 'jeddah-season-2026',
    baseId: 'jeddah-season-2026',
    title: 'Jeddah Season 2026',
    titleAr: 'موسم جدة ٢٠٢٦',
    targetDate: '2026-07-01T00:00:00',
    icon: '🎡',
    theme: 'sunset',
    category: 'entertainment',
    dateConfidence: 'tentative',
    dateSource: 'GEA (Expected Annual)',
    note: 'موسم جدة الترفيهي الصيفي - فعاليات متنوعة على البحر الأحمر',
    recurrenceType: 'one-time',
  },
  {
    id: 'red-sea-film-festival-2026',
    baseId: 'red-sea-film-festival-2026',
    title: 'Red Sea International Film Festival 2026',
    titleAr: 'مهرجان البحر الأحمر السينمائي ٢٠٢٦',
    targetDate: '2026-11-10T00:00:00',
    icon: '🎬',
    theme: 'night',
    category: 'entertainment',
    dateConfidence: 'tentative',
    dateSource: 'Red Sea Film Foundation',
    note: 'مهرجان السينما الأبرز في الشرق الأوسط - جدة',
    recurrenceType: 'one-time',
  },
  {
    id: 'mdl-beast-2026',
    baseId: 'mdl-beast-2026',
    title: 'MDL Beast 2026',
    titleAr: 'مهرجان MDL Beast ٢٠٢٦',
    targetDate: '2026-12-11T00:00:00',
    icon: '🎵',
    theme: 'night',
    category: 'entertainment',
    dateConfidence: 'tentative',
    dateSource: 'MDL Beast (Expected Annual)',
    note: 'أكبر مهرجان موسيقي في الشرق الأوسط - الرياض',
    recurrenceType: 'one-time',
  },
  {
    id: 'winter-tantora-alula-2026', baseId: 'winter-tantora-alula-2026',
    title: 'Winter at Tantora AlUla 2026', titleAr: 'شتاء طنطورة العُلا ٢٠٢٦',
    targetDate: '2026-12-20T00:00:00',
    icon: '🏺', theme: 'sunset', category: 'entertainment',
    dateConfidence: 'tentative', dateSource: 'Royal Commission for AlUla (Expected Annual)',
    note: 'مهرجان شتاء طنطورة في العُلا - موسيقى وثقافة وتراث',
    recurrenceType: 'one-time',
  },
  {
    id: 'formula-e-riyadh-2027',
    baseId: 'formula-e-riyadh-2027',
    title: 'Formula E Riyadh E-Prix 2027',
    titleAr: 'سباق الفورمولا E الرياض ٢٠٢٧',
    targetDate: '2027-02-05T00:00:00',
    icon: '⚡',
    theme: 'night',
    category: 'entertainment',
    dateConfidence: 'tentative',
    dateSource: 'Formula E (Expected Annual)',
    note: 'سباق الفورمولا إي للسيارات الكهربائية في قلب الرياض',
    recurrenceType: 'one-time',
  },
];

/**
 * @deprecated Use processEventsWithRecurrence from eventRecurrenceEngine instead
 * Get upcoming events (legacy - static filter)
 */
export const getUpcomingEvents = (): PublicEvent[] => {
  const now = new Date();
  return publicEvents
    .filter((event) => new Date(event.targetDate) > now)
    .sort((a, b) => new Date(a.targetDate).getTime() - new Date(b.targetDate).getTime());
};

/**
 * Get events by category
 */
export const getEventsByCategory = (category: PublicEvent['category']): PublicEvent[] => {
  return publicEvents.filter((event) => event.category === category);
};
